### ISSUE TITLE
Album art not working on spotify

### ISSUE THREAD

**Issue by youpie** [StreamController/MediaPlugin#1]
Hi,,

When using the media info tile and enabling the 'show thumbnail of currently playing song' option. It does not work for spotify. Interestingly, it does work for spotify web on firefox.

I use gnome on wayland and the spotify flatpak

![image](https://github.com/StreamController/StreamController/assets/37704067/0e725f89-6109-4818-a8a7-28c2c36388f2)
When using spotify web

![image](https://github.com/StreamController/StreamController/assets/37704067/416277e3-e06c-40ed-97c8-c016e2c2496f)
When using spotify app

**Comment by oparada1988** [comment]
Can replicate, however the album art does not work on chrome

**Comment by Core447** [comment]
Thanks for reporting this! I'm working on a solution.

**Comment by Core447** [comment]
Should be fixed with 93d6aae8c72d8be2def7bd962ce8b4fdf0754f99. Could you please check if it works for you? Just update the plugin in the store and restart the app.

**Comment by youpie** [comment]
> Should be fixed with [93d6aae](https://github.com/StreamController/MediaPlugin/commit/93d6aae8c72d8be2def7bd962ce8b4fdf0754f99). Could you please check if it works for you? Just update the plugin in the store and restart the app.

It works now, thank you very much for your work!
