### ISSUE TITLE
Album Art & Song description does not update

### ISSUE THREAD

**Issue by oparada1988** [StreamController/MediaPlugin#2]
When the next song plays, the album, song name, and artist name does not update

https://github.com/StreamController/MediaPlugin/assets/4031078/b426408e-92c0-4ae1-b993-455f7d1fa068

**Comment by Core447** [comment]
Does it work for media playing from Firefox or any other player?

**Comment by oparada1988** [comment]
> Does it work for media playing from Firefox or any other player?

It does not detect the web browser(chrome) when playing music as a player

**Comment by oparada1988** [comment]
Rebooting my system fixed the issue, Not sure if something happened on my previous session. How do I go about capturing logs for you to review?

**Comment by Core447** [comment]
The best way is to launch StreamController from the command line, but you can copy the logs from the Troubleshooting section of the about screen as well.

**Comment by oparada1988** [comment]
Thanks, I will close this and continue to monitor and will open a new issue if ti occurs again.
