### ISSUE TITLE
bug - thumbnail doesnt exist, spamming console

### ISSUE THREAD

**Issue by merlinlcb** [StreamController/MediaPlugin#3]
**Describe the bug**
When album art is not available console is spammed

**Screenshots**
![image](https://github.com/StreamController/StreamController/assets/5841146/48d8205b-4050-490c-a0bb-de2375c2420e)

**Comment by Core447** [comment]
I checked it and crunchyroll is indeed not setting a thumbnail. So unfortunately there's nothing I can do to make it work.

**Comment by merlinlcb** [comment]
The intent wasnt to fix it, but maybe suppress the attempts to set the thumbnail when the audio provider isnt supplying it? Im sure not many other care about it spamming the console

**Comment by Core447** [comment]
Ok, yeah I'll fix the spamming

**Comment by Core447** [comment]
Should be fixed in 0e5eeb4ec488d3dd31b4005b9827271c543e53b6
